### ISSUE TITLE
Add Figma Design starter

### ISSUE THREAD

**Issue by arlindmusliu** [lucky-media/guidelines#5]
But, make sure you explain it as talking to a junior developer, not a designer.

You can write it here, if you don't want to dive into VSCode and deploying it locally:
[MarkDown Editor Online](https://stackedit.io/app#)

**Comment by artzenki** [comment]
Will do. I started the Guideline by explaining for 'Future Designers', but I will add the explanation on how the Devs should interact and prepare the configuration for future development projects, and where they can navigate into finding the proper configuration of the Project.
